CC=gcc

all:
	# $(CC) -I/Library/Frameworks/Python.framework/Headers -o parsetuple parsetuple.c
	$(CC) -I/Library/Frameworks/Python.framework/Headers -o custom_function custom_function.c



parsetuple:
	$(CC) -I/Library/Frameworks/Python.framework/Versions/3.8/Headers -L/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/config-3.8-darwin -lpython3.8 -o parsetuple parsetuple.c
