CC=gcc


all:
	$(CC) -I/usr/local/include -L/Users/YoungChanPark/tools/htslib -lhts -o read_bam read_bam.c
	$(CC) -I/usr/local/include -L/Users/YoungChanPark/tools/htslib -lhts -o read_bam_cigar read_bam_cigar.c
	$(CC) -I/usr/local/include -L/Users/YoungChanPark/tools/htslib -lhts -o splitting_read_ratio splitting_read_ratio.c
